### ISSUE TITLE
MacOS Metal issue

### ISSUE THREAD

**Issue by ZelimDamian** [Chaser324/unity-wireframe#2]
Shaders don't seem to work with Metal on MacOS.
Switching graphics api to OpenGL fixes the issue.
![image](https://user-images.githubusercontent.com/2415231/34411632-eab5a452-ebe8-11e7-9e7e-e031f90cb967.png)

**Comment by Chaser324** [comment]
Metal only supports up to Shader Model 3.5, and as noted in the README,
these shaders require Shader Model 4.0.

See this page for more info on the max Shader Model supported by given
platforms: https://docs.unity3d.com/Manual/SL-ShaderCompileTargets.html
